---
title: "Characteristics Tables"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages 
```{r}
library(dplyr)
library(finalfit)
```

### 2. SPHC-C 2010
```{r}

```

### 3. SPHC-C 2014
```{r}
nrow( d_2014 )


```

### 4. SPHC-C 2021
```{r}
nrow( d_2021 )


```

### 5. Comparison across Surveys
#### 5.1. Heterosexual group
```{r}
# Fisher's test
# sex
x1 <- cbind( as.data.frame.matrix( table( d_2010$sex, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$sex, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$sex, d_2021$sexual_identity ) ) )

format( round( fisher.test( x1[, c( 1, 5 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 1, 9 ) ] )$p.value, 3 ), nsmall = 3 )

# age
x2 <- cbind( as.data.frame.matrix( table( d_2010$age_cat, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$age_cat, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$age_cat, d_2021$sexual_identity ) ) )

format( round( fisher.test( x2[, c( 1, 5 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 1, 9 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# country of birth
x3 <- cbind( as.data.frame.matrix( table( d_2010$country_of_birth, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$country_of_birth, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$country_of_birth, d_2021$sexual_identity ) ) )

format( round( fisher.test( x3[, c( 1, 5 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 1, 9 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# education
x4 <- cbind( as.data.frame.matrix( table( d_2010$education, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$education, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$education, d_2021$sexual_identity ) ) )

format( round( fisher.test( x4[, c( 1, 5 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 1, 9 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# income
x5 <- cbind( as.data.frame.matrix( table( d_2010$income, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$income, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$income, d_2021$sexual_identity ) ) )

format( round( fisher.test( x5[, c( 1, 5 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 1, 9 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# marital status
x6 <- cbind( as.data.frame.matrix( table( d_2010$marital_status, d_2010$sexual_identity ) ),
             as.data.frame.matrix( table( d_2014$marital_status, d_2014$sexual_identity ) ),
             as.data.frame.matrix( table( d_2021$marital_status, d_2021$sexual_identity ) ) )

format( round( fisher.test( x6[, c( 1, 5 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 1, 9 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
```

#### 5.2. Homosexual group
```{r}
# Fisher's test
# sex
format( round( fisher.test( x1[, c( 2, 6 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 2, 10 ) ] )$p.value, 3 ), nsmall = 3 )

# age
format( round( fisher.test( x2[, c( 2, 6 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 2, 10 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# country of birth
format( round( fisher.test( x3[, c( 2, 6 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 2, 10 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# education
format( round( fisher.test( x4[, c( 2, 6 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 2, 10 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# income
format( round( fisher.test( x5[, c( 2, 6 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 2, 10 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# marital status
format( round( fisher.test( x6[, c( 2, 6 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 2, 10 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
```

#### 5.3. Bisexual group
```{r}
# Fisher's test
# sex
format( round( fisher.test( x1[, c( 3, 7 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 3, 11 ) ] )$p.value, 3 ), nsmall = 3 )

# age
format( round( fisher.test( x2[, c( 3, 7 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 3, 11 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# country of birth
format( round( fisher.test( x3[, c( 3, 7 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 3, 11 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# education
format( round( fisher.test( x4[, c( 3, 7 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 3, 11 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# income
format( round( fisher.test( x5[, c( 3, 7 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 3, 11 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# marital status
format( round( fisher.test( x6[, c( 3, 7 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 3, 11 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
```

#### 5.4. Uncertain/neither group
```{r}
# Fisher's test
# sex
format( round( fisher.test( x1[, c( 4, 8 ) ] )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x1[, c( 4, 12 ) ] )$p.value, 3 ), nsmall = 3 )

# age
format( round( fisher.test( x2[, c( 4, 8 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x2[, c( 4, 12 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# country of birth
format( round( fisher.test( x3[, c( 4, 8 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x3[, c( 4, 12 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# education
format( round( fisher.test( x4[, c( 4, 8 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x4[, c( 4, 12 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# income
format( round( fisher.test( x5[, c( 4, 8 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x5[, c( 4, 12 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )

# marital status
format( round( fisher.test( x6[, c( 4, 8 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
format( round( fisher.test( x6[, c( 4, 12 ) ], simulate.p.value = TRUE )$p.value, 3 ), nsmall = 3 )
```