---
title: "Fluidity of Self-Reported Sexual Identity in Stockholm County from 2010 to 2021"
author: Guoqiang Zhang (guoqiang.zhang@ki.se)
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(haven)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggalluvial)
library(ggbreak)
library(ggrepel)
```

### 2. The Stockholm Public Health Cohort
```{r}
# NOTES: 'SPHC-B + year' refers to the baseline survey in the Stockholm Public Health Cohort (SPHC); for example, SPHC-B 2010 represents the baseline survey in 2010. 'SPHC-F + year' refers to the follow-up survey; for example, SPHC-F 2014 represents the follow-up survey in 2014.

### SPHC-B 2002 with SPHC-F 2010-2021 ###
# d_2002 <- read_sas("G:/CES/SRHR/SPHC LGBTQ health data/sphc02_07_10_14_21.sas7bdat")

# sex
table( d_2002$kon, useNA = "always" )
d_2002$sex <- factor( ifelse( d_2002$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2002$sex, useNA = "always" )

# age
summary( d_2002$F2alder )
d_2002$age_2002 <- d_2002$F2alder
d_2002$age_2010 <- d_2002$age_2002 + 8
d_2002$age_2014 <- d_2002$age_2002 + 12
d_2002$age_2010_cat <- factor( ifelse( d_2002$age_2010 <= 29, "16-29", 
                                       ifelse( d_2002$age_2010 >=30 & d_2002$age_2010 <= 44, "30-44",
                                               ifelse( d_2002$age_2010 >= 45 & d_2002$age_2010 <= 59, "45-59", ">=60" ) ) ),
                               levels = c( "16-29", "30-44", "45-59", ">=60" ) )
table( d_2002$age_2010_cat, useNA = "always" )

# sexual identity in 2010
table( d_2002$F10F103, useNA = "always" )
d_2002$F10F103[ d_2002$F10F103 == 9 ] <- NA
d_2002$sexual_identity_2010 <- factor( ifelse( d_2002$F10F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F10F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F10F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2002$F14F103, useNA = "always" )
d_2002$sexual_identity_2014 <- factor( ifelse( d_2002$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2002$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2002$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2002$F21F91, useNA = "always" )
d_2002$sexual_identity_2021 <- factor( ifelse( d_2002$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2002$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2002$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2002$sexual_identity_2021, useNA = "always" )


### SPHC-B 2006 with SPHC-F 2010-2021 ###
# d_2006 <- read_sas("G:/CES/SRHR/SPHC LGBTQ health data/sphc06_10_14_21.sas7bdat")

# sex
table( d_2006$kon, useNA = "always" )
d_2006$sex <- factor( ifelse( d_2006$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2006$sex, useNA = "always" )

# age
summary( d_2006$F6alder )
d_2006$age_2006 <- d_2006$F6alder
d_2006$age_2010 <- d_2006$age_2006 + 4
d_2006$age_2014 <- d_2006$age_2006 + 8
d_2006$age_2010_cat <- factor( ifelse( d_2006$age_2010 <= 29, "16-29", 
                                       ifelse( d_2006$age_2010 >=30 & d_2006$age_2010 <= 44, "30-44",
                                               ifelse( d_2006$age_2010 >= 45 & d_2006$age_2010 <= 59, "45-59", ">=60" ) ) ),
                               levels = c( "16-29", "30-44", "45-59", ">=60" ) )
table( d_2006$age_2010_cat, useNA = "always" )

# sexual identity in 2010
table( d_2006$F10F103, useNA = "always" )
d_2006$F10F103[ d_2006$F10F103 == 9 ] <- NA
d_2006$sexual_identity_2010 <- factor( ifelse( d_2006$F10F103 == 1, "Heterosexual",
                                                  ifelse( d_2006$F10F103 == 2, "Homosexual",
                                                          ifelse( d_2006$F10F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2006$F14F103, useNA = "always" )
d_2006$sexual_identity_2014 <- factor( ifelse( d_2006$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2006$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2006$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2006$F21F91, useNA = "always" )
d_2006$sexual_identity_2021 <- factor( ifelse( d_2006$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2006$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2006$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2006$sexual_identity_2021, useNA = "always" )


### SPHC-B 2010 with SPHC-F 2014-2021 ###
# d_2010 <- read_sas("G:/CES/SRHR/SPHC LGBTQ health data/sphc10_14_21.sas7bdat")

# sex
table( d_2010$kon, useNA = "always" )
d_2010$sex <- factor( ifelse( d_2010$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2010$sex, useNA = "always" )

# age
summary( d_2010$F10alder )
d_2010$age_2010 <- d_2010$F10alder
d_2010$age_2014 <- d_2010$age_2010 + 4
d_2010$age_2010_cat <- factor( ifelse( d_2010$age_2010 <= 29, "16-29", 
                                       ifelse( d_2010$age_2010 >=30 & d_2010$age_2010 <= 44, "30-44",
                                               ifelse( d_2010$age_2010 >= 45 & d_2010$age_2010 <= 59, "45-59", ">=60" ) ) ),
                               levels = c( "16-29", "30-44", "45-59", ">=60" ) )
table( d_2010$age_2010_cat, useNA = "always" )

# sexual identity in 2010
table( d_2010$F10U87G78, useNA = "always" )
d_2010$F10U87G78[ d_2010$F10U87G78 == 9 ] <- NA
d_2010$sexual_identity_2010 <- factor( ifelse( d_2010$F10U87G78 == 1, "Heterosexual",
                                                  ifelse( d_2010$F10U87G78 == 2, "Homosexual",
                                                          ifelse( d_2010$F10U87G78 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2010, useNA = "always" )

# sexual identity in 2014
table( d_2010$F14F103, useNA = "always" )
d_2010$sexual_identity_2014 <- factor( ifelse( d_2010$F14F103 == 1, "Heterosexual",
                                                  ifelse( d_2010$F14F103 == 2, "Homosexual",
                                                          ifelse( d_2010$F14F103 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2010$F21F91, useNA = "always" )
d_2010$sexual_identity_2021 <- factor( ifelse( d_2010$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2010$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2010$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2010$sexual_identity_2021, useNA = "always" )


### SPHC-B 2014 with SPHC-F 2021 ###
# d_2014 <- read_sas("G:/CES/SRHR/SPHC LGBTQ health data/sphc14_21.sas7bdat")

# sex
table( d_2014$kon, useNA = "always" )
d_2014$sex <- factor( ifelse( d_2014$kon == 1, "Male", "Female" ),
                      levels = c( "Male", "Female" ) )
table( d_2014$sex, useNA = "always" )

# age
summary( d_2014$F14alder )
d_2014$age_2014 <- d_2014$F14alder

# sexual identity in 2014
table( d_2014$F14U90G82, useNA = "always" )
d_2014$sexual_identity_2014 <- factor( ifelse( d_2014$F14U90G82 == 1, "Heterosexual",
                                                  ifelse( d_2014$F14U90G82 == 2, "Homosexual",
                                                          ifelse( d_2014$F14U90G82 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2014$sexual_identity_2014, useNA = "always" )

# sexual identity in 2021
table( d_2014$F21F91, useNA = "always" )
d_2014$sexual_identity_2021 <- factor( ifelse( d_2014$F21F91 == 1, "Heterosexual",
                                                  ifelse( d_2014$F21F91 == 2, "Homosexual",
                                                          ifelse( d_2014$F21F91 == 3, "Bisexual", "Other" ) ) ),
                                          levels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ) )
table( d_2014$sexual_identity_2021, useNA = "always" )
```

### 3. Fluidity of Sexual Identity
#### 3.1. Prepare datasets for plotting
```{r}
### 2010-2014 ###
# based on respondents who reported sexual identity in SPHC-F 2010 and 2014 from SPHC-B 2002, 2006 and 2010
# including those in SPHC-B 2010
n1 <- as.data.frame( table( d_2002$sexual_identity_2010, d_2002$sexual_identity_2014 ) )
n1$year <- rep( "SPHC-B 2002", nrow( n1 ) )

n2 <- as.data.frame( table( d_2006$sexual_identity_2010, d_2006$sexual_identity_2014 ) )
n2$year <- rep( "SPHC-B 2006", nrow( n2 ) )

n3 <- as.data.frame( table( d_2010$sexual_identity_2010, d_2010$sexual_identity_2014 ) )
n3$year <- rep( "SPHC-B 2010", nrow( n3 ) )

n123 <- merge( n1, merge( n2, n3, by = c( "Var1", "Var2" ) ),  by = c( "Var1", "Var2" ) )
n123$number <- n123$Freq + n123$Freq.x + n123$Freq.y
n123 <- n123 %>% select( "Var1", "Var2", "number" )
colnames( n123 ) <- c( "sexual_identity_2010", "sexual_identity_2014", "number" )
sum( n123$number ) # 48,078 respondents
n123$percent <- n123$number/sum( n123$number )

for ( col in 1:2 ) {
  n123[[col]] <- factor( n123[[col]], levels = c( "Homosexual", "Bisexual", "Other", "Heterosexual" ) ) 
}

n123$percent_for_label <- ifelse( n123$sexual_identity_2010 == "Heterosexual",
                                  n123$number/sum( n123[ n123$sexual_identity_2010 == "Heterosexual", ]$number ),
                                  ifelse( n123$sexual_identity_2010 == "Homosexual", 
                                          n123$number/sum( n123[ n123$sexual_identity_2010 == "Homosexual", ]$number ),
                                          ifelse( n123$sexual_identity_2010 == "Bisexual", 
                                                  n123$number/sum( n123[ n123$sexual_identity_2010 == "Bisexual", ]$number ),
                                                  n123$number/sum( n123[ n123$sexual_identity_2010 == "Other", ]$number ) ) ) )

n123$label <- paste0( prettyNum( n123$number, big.mark = "," , preserve.width = "none" ), " (", 
                      sprintf( "%.1f", n123$percent_for_label*100 ), "%)" )

n123_long <- to_lodes_form( n123, axes = 1:2, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format


### 2014-2021 ###
# based on respondents who reported sexual identity in SPHC-F 2014 and 2021 from SPHC-B 2002, 2006, 
# 2010 and 2014, including those in SPHC-B 2014
n4 <- as.data.frame( table( d_2002$sexual_identity_2014, d_2002$sexual_identity_2021 ) )
n4$year <- rep( "SPHC-B 2002", nrow( n4 ) )

n5 <- as.data.frame( table( d_2006$sexual_identity_2014, d_2006$sexual_identity_2021 ) )
n5$year <- rep( "SPHC-B 2006", nrow( n5 ) )

n6 <- as.data.frame( table( d_2010$sexual_identity_2014, d_2010$sexual_identity_2021 ) )
n6$year <- rep( "SPHC-B 2010", nrow( n6 ) )

n7 <- as.data.frame( table( d_2014$sexual_identity_2014, d_2014$sexual_identity_2021 ) )
n7$year <- rep( "SPHC-B 2014", nrow( n7 ) )

n4567 <- merge( n4, merge( n5, merge( n6, n7, by = c( "Var1", "Var2" ), suffixes = c( "_c", "_d" ) ), 
                           by = c( "Var1", "Var2" ) ),  by = c( "Var1", "Var2" ), suffixes = c( "_a", "_b" ) )
n4567$number <- n4567$Freq_a + n4567$Freq_b + n4567$Freq_c + n4567$Freq_d
n4567 <- n4567 %>% select( "Var1", "Var2", "number" )
colnames( n4567 ) <- c( "sexual_identity_2014", "sexual_identity_2021", "number" )
sum( n4567$number ) # 49,104 respondents
n4567$percent <- n4567$number/sum( n4567$number )

for ( col in 1:2 ) {
  n4567[[col]] <- factor( n4567[[col]], levels = c( "Homosexual", "Bisexual", "Other", "Heterosexual" ) ) 
}

n4567$percent_for_label <- ifelse( n4567$sexual_identity_2014 == "Heterosexual",
                                  n4567$number/sum( n4567[ n4567$sexual_identity_2014 == "Heterosexual", ]$number ),
                                  ifelse( n4567$sexual_identity_2014 == "Homosexual", 
                                          n4567$number/sum( n4567[ n4567$sexual_identity_2014 == "Homosexual", ]$number ),
                                          ifelse( n4567$sexual_identity_2014 == "Bisexual", 
                                                  n4567$number/sum( n4567[ n4567$sexual_identity_2014 == "Bisexual", ]$number ),
                                                  n4567$number/sum( n4567[ n4567$sexual_identity_2014 == "Other", ]$number ) ) ) )

n4567$label <- paste0( prettyNum( n4567$number, big.mark = "," , preserve.width = "none" ), " (", 
                      sprintf( "%.1f", n4567$percent_for_label*100 ), "%)" )

n4567_long <- to_lodes_form( n4567, axes = 1:2, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2014 ) # convert to long format


### 2010-2021 ###
# based on respondents who reported sexual identity in SPHC-F 2010, 2014 and 2021 from SPHC-B 2002, 2006 
# and 2010, including those in SPHC-B 2010
m1 <- d_2002[ !is.na(d_2002$sexual_identity_2010) & !is.na(d_2002$sexual_identity_2014) & !is.na(d_2002$sexual_identity_2021), c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "age_2010" ) ]
m1$year <- rep( "SPHC-B 2002", nrow(m1) )

m2 <- d_2006[ !is.na(d_2006$sexual_identity_2010) & !is.na(d_2006$sexual_identity_2014) & !is.na(d_2006$sexual_identity_2021), c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "age_2010" ) ]
m2$year <- rep( "SPHC-B 2006", nrow(m2) )

m3 <- d_2010[ !is.na(d_2010$sexual_identity_2010) & !is.na(d_2010$sexual_identity_2014) & !is.na(d_2010$sexual_identity_2021), c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "age_2010" ) ]
m3$year <- rep( "SPHC-B 2010", nrow(m3) )

m123 <- full_join( m1, full_join( m2, m3, by = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "age_2010", "year" ) ), by = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "age_2010", "year" ) )

summary( m123$age_2010 )
m123$age_2010_cat <- factor( ifelse( m123$age_2010 <= 29, "16-29", 
                                     ifelse( m123$age_2010 >=30 & m123$age_2010 <= 44, "30-44",
                                             ifelse( m123$age_2010 >= 45 & m123$age_2010 <= 59, "45-59", ">=60" ) ) ),
                             levels = c( "16-29", "30-44", "45-59", ">=60" ) )
table( m123$age_2010_cat, useNA = "always" )

# among all respondents
m123_all <- as.data.frame( table( m123$sexual_identity_2010, m123$sexual_identity_2014, m123$sexual_identity_2021 ) ) # wide format
colnames( m123_all ) <- c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "number" )
m123_all$percent <- m123_all$number/sum( m123_all$number )
m123_all$percent_for_label <- ifelse( m123_all$sexual_identity_2010 == "Heterosexual", 
                                      m123_all$number/sum( m123_all[ m123_all$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_all$sexual_identity_2010 == "Homosexual", 
                                              m123_all$number/sum( m123_all[ m123_all$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_all$sexual_identity_2010 == "Bisexual", 
                                                      m123_all$number/sum( m123_all[ m123_all$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_all$number/sum( m123_all[ m123_all$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_all$label <- paste0( prettyNum( m123_all$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_all$percent_for_label*100 ),
                          "%)" )

for ( col in 1:3 ) {
  m123_all[[col]] <- factor( m123_all[[col]], levels = c( "Homosexual", "Bisexual", "Other", "Heterosexual" ) ) 
}

m123_all_long <- to_lodes_form( m123_all, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

# by sex
m123_sex <- as.data.frame( table( m123$sexual_identity_2010, m123$sexual_identity_2014, m123$sexual_identity_2021, m123$sex ) )
colnames( m123_sex ) <- c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "sex", "number" )

m123_sex$percent <- ifelse( m123_sex$sex == "Male", m123_sex$number/sum( m123_sex[ m123_sex$sex == "Male", ]$number ),
                            m123_sex$number/sum( m123_sex[ m123_sex$sex == "Female", ]$number ) )

for ( col in 1:3 ) {
  m123_sex[[col]] <- factor( m123_sex[[col]], levels = c( "Homosexual", "Bisexual", "Other", "Heterosexual" ) ) 
}

m123_male <- m123_sex[ m123_sex$sex == "Male", ]
m123_male$percent_for_label <- ifelse( m123_male$sexual_identity_2010 == "Heterosexual", 
                                      m123_male$number/sum( m123_male[ m123_male$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_male$sexual_identity_2010 == "Homosexual", 
                                              m123_male$number/sum( m123_male[ m123_male$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_male$sexual_identity_2010 == "Bisexual", 
                                                      m123_male$number/sum( m123_male[ m123_male$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_male$number/sum( m123_male[ m123_male$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_male$label <- paste0( prettyNum( m123_male$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_male$percent_for_label*100 ),
                          "%)" )

m123_female <- m123_sex[ m123_sex$sex == "Female", ]
m123_female$percent_for_label <- ifelse( m123_female$sexual_identity_2010 == "Heterosexual", 
                                      m123_female$number/sum( m123_female[ m123_female$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_female$sexual_identity_2010 == "Homosexual", 
                                              m123_female$number/sum( m123_female[ m123_female$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_female$sexual_identity_2010 == "Bisexual", 
                                                      m123_female$number/sum( m123_female[ m123_female$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_female$number/sum( m123_female[ m123_female$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_female$label <- paste0( prettyNum( m123_female$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_female$percent_for_label*100 ),
                          "%)" )

m123_male_long <- to_lodes_form( m123_male, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

m123_female_long <- to_lodes_form( m123_female, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

# by age
m123_age <- as.data.frame( table( m123$sexual_identity_2010, m123$sexual_identity_2014, m123$sexual_identity_2021, m123$age_2010_cat ) )
colnames( m123_age ) <- c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021", "age_group", "number" )

m123_age$percent <- ifelse( m123_age$age_group == "16-29", m123_age$number/sum( m123_age[ m123_age$age_group == "16-29", ]$number ),
                            ifelse( m123_age$age_group == "30-44", m123_age$number/sum( m123_age[ m123_age$age_group == "30-44", ]$number ), 
                                    ifelse( m123_age$age_group == "45-59", m123_age$number/sum( m123_age[ m123_age$age_group == "45-59", ]$number ),
                                            m123_age$number/sum( m123_age[ m123_age$age_group == ">=60", ]$number ) ) ) )

for ( col in 1:3 ) {
  m123_age[[col]] <- factor( m123_age[[col]], levels = c( "Homosexual", "Bisexual", "Other", "Heterosexual" ) ) 
}

m123_age_18 <- m123_age[ m123_age$age_group == "16-29", ]
m123_age_18$percent_for_label <- ifelse( m123_age_18$sexual_identity_2010 == "Heterosexual", 
                                      m123_age_18$number/sum( m123_age_18[ m123_age_18$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_age_18$sexual_identity_2010 == "Homosexual", 
                                              m123_age_18$number/sum( m123_age_18[ m123_age_18$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_age_18$sexual_identity_2010 == "Bisexual", 
                                                      m123_age_18$number/sum( m123_age_18[ m123_age_18$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_age_18$number/sum( m123_age_18[ m123_age_18$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_age_18$label <- paste0( prettyNum( m123_age_18$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_age_18$percent_for_label*100 ),
                          "%)" )

m123_age_30 <- m123_age[ m123_age$age_group == "30-44", ]
m123_age_30$percent_for_label <- ifelse( m123_age_30$sexual_identity_2010 == "Heterosexual", 
                                      m123_age_30$number/sum( m123_age_30[ m123_age_30$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_age_30$sexual_identity_2010 == "Homosexual", 
                                              m123_age_30$number/sum( m123_age_30[ m123_age_30$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_age_30$sexual_identity_2010 == "Bisexual", 
                                                      m123_age_30$number/sum( m123_age_30[ m123_age_30$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_age_30$number/sum( m123_age_30[ m123_age_30$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_age_30$label <- paste0( prettyNum( m123_age_30$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_age_30$percent_for_label*100 ),
                          "%)" )

m123_age_45 <- m123_age[ m123_age$age_group == "45-59", ]
m123_age_45$percent_for_label <- ifelse( m123_age_45$sexual_identity_2010 == "Heterosexual", 
                                      m123_age_45$number/sum( m123_age_45[ m123_age_45$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_age_45$sexual_identity_2010 == "Homosexual", 
                                              m123_age_45$number/sum( m123_age_45[ m123_age_45$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_age_45$sexual_identity_2010 == "Bisexual", 
                                                      m123_age_45$number/sum( m123_age_45[ m123_age_45$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_age_45$number/sum( m123_age_45[ m123_age_45$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_age_45$label <- paste0( prettyNum( m123_age_45$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_age_45$percent_for_label*100 ),
                          "%)" )

m123_age_60 <- m123_age[ m123_age$age_group == ">=60", ]
m123_age_60$percent_for_label <- ifelse( m123_age_60$sexual_identity_2010 == "Heterosexual", 
                                      m123_age_60$number/sum( m123_age_60[ m123_age_60$sexual_identity_2010 == "Heterosexual", ]$number ),
                                      ifelse( m123_age_60$sexual_identity_2010 == "Homosexual", 
                                              m123_age_60$number/sum( m123_age_60[ m123_age_60$sexual_identity_2010 == "Homosexual", ]$number ),
                                              ifelse( m123_age_60$sexual_identity_2010 == "Bisexual", 
                                                      m123_age_60$number/sum( m123_age_60[ m123_age_60$sexual_identity_2010 == "Bisexual", ]$number ),
                                                      m123_age_60$number/sum( m123_age_60[ m123_age_60$sexual_identity_2010 == "Other", ]$number ) ) ) )

m123_age_60$label <- paste0( prettyNum( m123_age_60$number, big.mark = "," , preserve.width = "none" ), " (", 
                          sprintf( "%.1f", m123_age_60$percent_for_label*100 ),
                          "%)" )

m123_age_18_long <- to_lodes_form( m123_age_18, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

m123_age_30_long <- to_lodes_form( m123_age_30, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

m123_age_45_long <- to_lodes_form( m123_age_45, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format

m123_age_60_long <- to_lodes_form( m123_age_60, axes = 1:3, key = "year", value = "sexual_identity", id = "Cohort", diffuse = sexual_identity_2010 ) # convert to long format
```

#### 3.2. Plotting
```{r}
### 2010-2014 ###
# among all respondents
ggplot( n123_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014" ), labels = c( "2010", "2014" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.9 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2014" & ( percent_for_label >= 0.1 | number >= 50 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


### 2014-2021 ###
# among all respondents
ggplot( n4567_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2014 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2014 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.9 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2014, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 50 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


### 2010-2021 ###
# among all respondents
ggplot( m123_all_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.9 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 50 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# among males
ggplot( m123_male_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.9 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 15 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# among females
ggplot( m123_female_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.9 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 30 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# 16-29 years 
ggplot( m123_age_18_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.86 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 6 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# 30-44 years
ggplot( m123_age_30_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.91 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 12 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# 45-59 years
ggplot( m123_age_45_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.91 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 15 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )


# >=60
ggplot( m123_age_60_long,
        aes( x = year,
             stratum = sexual_identity, 
             alluvium = Cohort,
             y = percent ) ) +
  geom_alluvium( aes( fill = sexual_identity_2010 ), curve_type = "cubic" ) +
  geom_stratum( aes( fill = sexual_identity_2010 ) ) +
  geom_text( stat = "stratum", aes( label = after_stat( stratum ) ), family = "Arial", size = 12 / .pt ) +
  scale_fill_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                     breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                     na.value = NA ) +
  scale_x_discrete( limits = c( "sexual_identity_2010", "sexual_identity_2014", "sexual_identity_2021" ), labels = c( "2010", "2014", "2021" ), expand = c( 0, 0 ) ) +
  theme_classic() +
  scale_y_break( c( 0.12, 0.88 ), scales = 10, space = 0.3 ) +
  scale_y_continuous( labels = scales::percent, breaks = c( 0, 0.1, 0.9, 0.95, 1 ) ) +
  labs( x = NULL, y = NULL) +
  theme( axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_blank(),
         legend.text = element_text( family = "Arial", size = 10 ), 
         legend.key = element_rect( colour = "white" ),
         legend.position = "bottom",
         axis.ticks.x.bottom = element_blank(),
         axis.line.x.bottom = element_blank(),
         axis.text.y.right = element_blank(),
         axis.ticks.y.right = element_blank(),
         axis.line.y.right = element_blank()
         ) +
  geom_text_repel( stat = "alluvium",
                   aes( color = factor( sexual_identity_2010, levels = c( "Other", "Bisexual", "Homosexual", "Heterosexual" ) ),
                        label = ifelse( year == "sexual_identity_2021" & ( percent_for_label >= 0.1 | number >= 20 ), label, NA ) ),
                   size = 4.5,
                   family = "Arial",
                   segment.linetype = 3,
                   segment.size = 0.55,
                   direction = "y",
                   nudge_x = 0.6,
                   box.padding = 0.5,
                   point.padding = 0,
                   show.legend = FALSE,
                   seed = 123
                   )
```

#### 3.3. Calculate proportion of changes in different sexual identity groups
```{r}
# define a function
calculate_proportion_change <- function( df_list, identities ) {
  
  # create an empty list to store the results
  results <- list()
  
  # loop through each data frame in the list
  for ( df_name in names( df_list ) ) {
    df <- df_list[[ df_name ]]
    
    # create an empty vector to store the proportions for each sexual identity
    proportions <- numeric( length( identities ) )
    names( proportions ) <- identities
    
    # loop through each sexual identity
    for ( identity in identities ) {
      
      # calculate the total number of individuals who identified as a specific identity in 2010
      n_identity <- sum( df[ df$sexual_identity_2010 == identity, ]$number )
      
      # skip this iteration if n_identity is zero to avoid division by zero
      if ( n_identity == 0 ) {
        next
      }
      
      # calculate the number of individuals who experienced a change in their sexual identity
      n_change <- sum( df[ df$sexual_identity_2010 == identity & 
                               df$sexual_identity_2021 != identity, ]$number )
      
      # calculate the proportion of individuals who experienced a change
      proportion_change <- n_change / n_identity
      
      proportions[ identity ] <- proportion_change
    }
    
    # store the proportions vector in the results list
    results[[ df_name ]] <- proportions
  }
  
  return( results )
}

# create a list of data frames
df_list <- list( "16-29" = m123_age_18, "30-44" = m123_age_30, "45-59" = m123_age_45, ">=60" = m123_age_60 )

# define the list of sexual identities to loop through
identities <- c( "Heterosexual", "Homosexual", "Bisexual", "Other" )

# calculate the proportion of individuals who experienced a change in sexual identity from 2010 to 2021
# for each sexual identity
results <- calculate_proportion_change( df_list, identities )

# convert the results to a dataframe
results_df <- bind_rows( results, .id = "Age_Group" )

results_long <- pivot_longer( results_df, 
                              cols = -Age_Group, 
                              names_to = "Sexual_Identity", 
                              values_to = "Proportion_Changed")

results_long$Age_Group <- factor( results_long$Age_Group, levels = c( "16-29", "30-44", "45-59", ">=60" ) )

ggplot( data = results_long, 
        aes( x = Age_Group, y = Proportion_Changed, group = Sexual_Identity, color = Sexual_Identity ) ) +
  
  scale_color_manual( values = c( "#C77CFF", "#00BFC4", "#7CAE00", "#F8766D" ),
                      breaks = c( "Heterosexual", "Homosexual", "Bisexual", "Other" ),
                      labels = c( "Heterosexual", "Homosexual", "Bisexual", "Other" )
                      ) +
  
  geom_line( linewidth = 1 ) + 
  geom_point( size = 3 ) +
  
  geom_hline( yintercept = 0.5, linetype = "dashed", color = "grey50", linewidth = 0.5 ) +

  scale_x_discrete( labels = c( "1629 years", "3044 years", "4559 years", "\u2265 60 years" ),
                    expand = c( 0.05, 0 )
                      ) +
  
  scale_y_continuous( labels = scales::percent,
                      limits = c( 0, 0.8 ), 
                      breaks = c( 0, 0.2, 0.4, 0.6, 0.8 ),
                      expand = c( 0, 0 ) ) +
  
  labs( x = "Age (years) in 2010",
        y = "Proportion (%) changed in 20102021" ) +

  theme_classic() +
  
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ),
         axis.text.y = element_text( family = "Arial", size = 11 ),
         axis.title.y = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ),
         legend.title = element_blank(),
         legend.position = "bottom"
         )
```