---
title: "R scripts for summary plots across surveys"
author: Guoqiang Zhang
email: guoqiang.zhang@ki.se
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### 1. Load Packages
```{r}
library(forestploter)
library(grid)
library(readxl)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(knitr)
```

### 2. Plots for Response Rates
```{r}
# datasets for response rates
sampling_frame_2010 <- read_excel("/Users/guoqiang.zhang/Library/CloudStorage/OneDrive-KarolinskaInstitutet/Karolinska Institutet/Research Projects/Prevalence and Fluidity of Sexual Identity/Sexual_Identity_R/sampling_frame_2010.xlsx")
sampling_frame_2014 <- read_excel("/Users/guoqiang.zhang/Library/CloudStorage/OneDrive-KarolinskaInstitutet/Karolinska Institutet/Research Projects/Prevalence and Fluidity of Sexual Identity/Sexual_Identity_R/sampling_frame_2014.xlsx")
sampling_frame_2021 <- read_excel("/Users/guoqiang.zhang/Library/CloudStorage/OneDrive-KarolinskaInstitutet/Karolinska Institutet/Research Projects/Prevalence and Fluidity of Sexual Identity/Sexual_Identity_R/sampling_frame_2021.xlsx")

combined_response_rate <- sampling_frame_2010[, c( 1, 6:8 ) ] %>% 
    full_join( sampling_frame_2014[, c( 1, 6:8 ) ], by = "sampling_strata_region" ) %>%
    full_join( sampling_frame_2021[, c( 1, 6:8 ) ], by = "sampling_strata_region" )

colnames( combined_response_rate ) <- c( "Municipality", 
                                         "unitresponse_rate_2010",
                                         "itemresponse_rate_2010",
                                         "overallresponse_rate_2010",
                                         "unitresponse_rate_2014",
                                         "itemresponse_rate_2014",
                                         "overallresponse_rate_2014",
                                         "unitresponse_rate_2021",
                                         "itemresponse_rate_2021",
                                         "overallresponse_rate_2021"
                                         )

str( combined_response_rate )

# Reshape to long format and extract the year
long_data <- combined_response_rate %>%
  tidyr::gather("Response rate", "Value", 
                starts_with("unitresponse_rate"), 
                starts_with("itemresponse_rate"), 
                starts_with("overallresponse_rate")) %>%
  tidyr::extract("Response rate", into = c("type", "year"), regex = "(.*)response_rate_(\\d{4})")

# Create the plot
# The rest of the data wrangling steps remain unchanged

# Adjust the plot creation
ggplot(long_data, aes(x = reorder(Municipality, -Value), 
                      y = Value, 
                      group = interaction(type, year), 
                      color = type, 
                      linetype = year)) +
  geom_line() +
  geom_point(aes(shape = year)) +
  coord_flip() +
  scale_y_continuous(limits = c(0.1, 1), breaks = c(0.3, 0.5, 0.7)) +
  scale_color_hue(labels = c("Item Response", "Overall Response", "Unit Response")) +
  labs(x = NULL, y = "Response Rate") +
  theme_minimal() +
  theme(axis.title.x = element_text(family = "Arial", size = 11),
        axis.text.x = element_text(family = "Arial", size = 11), 
        axis.text.y = element_text(family = "Arial", size = 11),
        legend.title = element_text(family = "Arial", size = 11),
        legend.text = element_text(family = "Arial", size = 10)) +
  guides(shape = guide_legend(override.aes = list(linetype = 0)))  # to remove linetype from shape legend




# visualize unit and overall response rate across sampling strata
ggplot( tidyr::gather( combined_response_rate, "Response rate", "Value", unitresponse_rate, overallresponse_rate ), 
        aes( x = reorder( sampling_strata_region, Value ), y = Value, group = `Response rate`, color = `Response rate` ) ) +
  geom_line() +
  geom_point() +
  coord_flip() +
  scale_y_continuous( limits = c( 0.3, 0.7 ), breaks = c( 0.3, 0.5, 0.7 ) ) +
  scale_color_hue( labels = c( "Unit & item response", "Unit response" ) ) +
  labs( x = NULL, y = "Response Rate" ) +
  theme_minimal() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ), 
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ) )


# visualize unit and overall response rate across sampling strata
ggplot( tidyr::gather( sampling_frame_2014, "Response rate", "Value", unitresponse_rate, overallresponse_rate ), 
        aes( x = reorder( sampling_strata_region, Value ), y = Value, group = `Response rate`, color = `Response rate` ) ) +
  geom_line() +
  geom_point() +
  coord_flip() +
  scale_y_continuous( limits = c( 0.2, 0.6 ), breaks = c( 0.2, 0.4, 0.6 ) ) +
  scale_color_hue( labels = c( "Unit & item response", "Unit response" ) ) +
  labs( x = NULL, y = "Response Rate" ) +
  theme_minimal() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ), 
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ) )

# visualize unit and overall response rate across sampling strata
ggplot( tidyr::gather( sampling_frame_2021, "Response rate", "Value", unitresponse_rate, overallresponse_rate ), 
        aes( x = reorder( sampling_strata_region, Value ), y = Value, group = `Response rate`, color = `Response rate` ) ) +
  geom_line() +
  geom_point() +
  coord_flip() +
  scale_y_continuous( limits = c( 0.2, 0.6 ), breaks = c( 0.2, 0.4, 0.6 ) ) +
  scale_color_hue( labels = c( "Unit & item response", "Unit response" ) ) +
  labs( x = NULL, y = "Response Rate" ) +
  theme_minimal() +
  theme( axis.title.x = element_text( family = "Arial", size = 11 ),
         axis.text.x = element_text( family = "Arial", size = 11 ), 
         axis.text.y = element_text( family = "Arial", size = 11 ),
         legend.title = element_text( family = "Arial", size = 11 ),
         legend.text = element_text( family = "Arial", size = 10 ) )
```

### 3. Forest Plots for Proportion of Sexual Identity
#### 3.1. Complete-case analysis
##### 3.1.1. Prepare dataset for plotting
```{r}
# datasets for proportion of sexual identity
prop_cc_summary_2010 <- read_excel("/Users/guoqiang.zhang/Documents/Karolinska Institutet/Research Projects/Trends and Fluidity of Sexual Identity/Sexual_identity_in_Stockholm_County/prop_cc_summary_2010.xlsx")
prop_cc_summary_2014 <- read_excel("/Users/guoqiang.zhang/Documents/Karolinska Institutet/Research Projects/Trends and Fluidity of Sexual Identity/Sexual_identity_in_Stockholm_County/prop_cc_summary_2014.xlsx")
prop_cc_summary_2021 <- read_excel("/Users/guoqiang.zhang/Documents/Karolinska Institutet/Research Projects/Trends and Fluidity of Sexual Identity/Sexual_identity_in_Stockholm_County/prop_cc_summary_2021.xlsx")

# to make it easier to combine across datasets
# a note on these changes will be added on the graph later
prop_cc_summary_2010$subgroup[ prop_cc_summary_2010$subgroup == "18-29" ] <- "16-29"
prop_cc_summary_2010$subgroup[ prop_cc_summary_2010$subgroup == "18-29.Male" ] <- "16-29.Male"
prop_cc_summary_2010$subgroup[ prop_cc_summary_2010$subgroup == "18-29.Female" ] <- "16-29.Female"

# merge datasets
prop_cc_summary <- prop_cc_summary_2010 %>%
  full_join( prop_cc_summary_2014, by = "subgroup" ) %>%
  full_join( prop_cc_summary_2021, by = "subgroup" )

# modify table format
desired_order <- c( "Male", "Female", "16-29", "30-44", "45-59", ">=60", "16-29.Male", "30-44.Male", "45-59.Male", ">=60.Male", "16-29.Female", "30-44.Female", "45-59.Female", ">=60.Female", "<=9 years", "10-12 years", ">=13 years", "Sweden", "Europe", "Outside Europe", "<=2,500", "(2,500, 3,500]", "(3,500, 4,500]", ">4,500", "Currently married", "Never married", "Other", "living_alone_yes", "living_alone_no", "personal_support_yes", "personal_support_no", "Stockholm County" )

prop_cc_summary <- prop_cc_summary %>%
  mutate( subgroup = factor( subgroup, levels = desired_order ) ) %>%
  arrange( subgroup )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Sex", .before = 1 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Age group", .before = 4 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Age by sex", .before = 9 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Education years", .before = 18 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Country of birth", .before = 22 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Income (100 kr/yr)ᵈ", .before = 26 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Marital statusᵉ", .before = 31 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Living alone", .before = 35 )

prop_cc_summary <- prop_cc_summary %>% 
  add_row( subgroup = "Personal support", .before = 38 )

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "16-29" ] <- "16–29 yrsᵇ"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "30-44" ] <- "30–44 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "45-59" ] <- "45–59 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == ">=60" ] <- "\u2265 60 yrs"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "16-29.Male" ] <- "Male: 16–29 yrsᵇ"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "30-44.Male" ] <- "Male: 30–44 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "45-59.Male" ] <- "Male: 45–59 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == ">=60.Male" ] <- "Male: \u2265 60 yrs"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "16-29.Female" ] <- "Female: 16–29 yrsᵇ"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "30-44.Female" ] <- "Female: 30–44 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "45-59.Female" ] <- "Female: 45–59 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == ">=60.Female" ] <- "Female: \u2265 60 yrs"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "<=9 years" ] <- "\u2264 9 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "10-12 years" ] <- "10–12 yrs"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == ">=13 years" ] <- "\u2265 13 yrs"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "Europe" ] <- "Europeᶜ"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "<=2,500" ] <- "\u2264 2,500"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == ">4,500" ] <- "> 4,500"

prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "living_alone_no" ] <- "No"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "living_alone_yes" ] <- "Yes"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "personal_support_no" ] <- "No"
prop_cc_summary$subgroup[ prop_cc_summary$subgroup == "personal_support_yes" ] <- "Yes"

prop_cc_summary$subgroup <- ifelse( is.na( prop_cc_summary$Heterosexual_point_estimate_2010 ) | 
                                      prop_cc_summary$subgroup == "Stockholm County", 
                                    prop_cc_summary$subgroup,
                                    paste0( "   ", prop_cc_summary$subgroup ) )

colnames( prop_cc_summary )[ colnames( prop_cc_summary ) == "subgroup" ] <- "Subgroup"

prop_cc_summary$sample_size_2010 <- ifelse( is.na( prop_cc_summary$sample_size_2010 ), "",
                                            prop_cc_summary$sample_size_2010 )

prop_cc_summary$sample_size_2014 <- ifelse( is.na( prop_cc_summary$sample_size_2014 ), "",
                                            prop_cc_summary$sample_size_2014 )

prop_cc_summary$sample_size_2021 <- ifelse( is.na( prop_cc_summary$sample_size_2021 ) &
                                              is.na( prop_cc_summary$Heterosexual_point_estimate_2010 ), "",
                                            ifelse( is.na( prop_cc_summary$sample_size_2021 ),  "\u2013",
                                                    prop_cc_summary$sample_size_2021 ) )
```

##### 3.1.2. Heterosexual group
```{r}
prop_cc_summary_heterosexual <- prop_cc_summary[ -c( 9:17 ), c( 1:4, 14:17, 27:30, 40 ) ]
  
prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 2 )
  
prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( "SPHC-B 2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_upper_ci_2010*100 ), ")" ),
    .before = 3 )

prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 8 )
  
prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( "SPHC-B 2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_upper_ci_2014*100 ), ")" ),
    .before = 9 )
  
prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 14 )
  
prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>% 
  add_column( "SPHC-B 2021" = paste0(
  sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_point_estimate_2021*100 ), " (", 
  sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_lower_ci_2021*100 ), ", ", 
  sprintf( "%.1f", prop_cc_summary_heterosexual$Heterosexual_upper_ci_2021*100 ), ")"  ),
  .before = 15 )

prop_cc_summary_heterosexual$`SPHC-B 2010` <- ifelse( 
  is.na( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2010 ), "",
  prop_cc_summary_heterosexual$`SPHC-B 2010` )

prop_cc_summary_heterosexual$`SPHC-B 2014` <- ifelse( 
  is.na( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2014 ), "",
  prop_cc_summary_heterosexual$`SPHC-B 2014` )

prop_cc_summary_heterosexual$`SPHC-B 2021` <- ifelse( 
  is.na( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2010 ) &
    is.na( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2021 ), "",
  ifelse( is.na( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2021 ), "\u2013",
          prop_cc_summary_heterosexual$`SPHC-B 2021` ) )

prop_cc_summary_heterosexual <- prop_cc_summary_heterosexual %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 8 ) %>%
  add_column( temp3 = " ", .before = 10 ) %>%
  add_column( temp4 = " ", .before = 16 ) %>%
  add_column( temp5 = " ", .before = 18 ) %>%
  add_column( temp6 = " ", .before = 24 )

names( prop_cc_summary_heterosexual )[ names( prop_cc_summary_heterosexual ) %in% c( "temp1", "temp2", "temp3", "temp4", "temp5", "temp6" ) ] <- ""

colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "SPHC-B 2010" ] <- ""
colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "SPHC-B 2014" ] <- ""
colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "SPHC-B 2021" ] <- ""

colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "sample_size_2010" ] <- ""
colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "sample_size_2014" ] <- ""
colnames( prop_cc_summary_heterosexual )[ colnames( prop_cc_summary_heterosexual ) == "sample_size_2021" ] <- ""

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ), 
  base_family = "Arial",
  ci_col = "red",
  refline_lty = "dotted",
  refline_lwd = 1,
  refline_col = "steelblue",
  vertline_lty = "dashed",
  vertline_lwd = 1,
  vertline_col = "steelblue",
  summary_col = "#4575b4",
  summary_fill = "#4575b4"
  )
  
p_cc_heterosexual <- forest(
  prop_cc_summary_heterosexual[ , c( 1:4, 8:12, 16:20, 24, 25 ) ],
    
  est = list( prop_cc_summary_heterosexual$Heterosexual_point_estimate_2010*100,
              prop_cc_summary_heterosexual$Heterosexual_point_estimate_2014*100,
              prop_cc_summary_heterosexual$Heterosexual_point_estimate_2021*100
              ),
  
  lower = list( prop_cc_summary_heterosexual$Heterosexual_lower_ci_2010*100,
                prop_cc_summary_heterosexual$Heterosexual_lower_ci_2014*100,
                prop_cc_summary_heterosexual$Heterosexual_lower_ci_2021*100
                ),
  
  upper = list( prop_cc_summary_heterosexual$Heterosexual_upper_ci_2010*100,
                prop_cc_summary_heterosexual$Heterosexual_upper_ci_2014*100,
                prop_cc_summary_heterosexual$Heterosexual_upper_ci_2021*100
                ),
  
  ci_column = c( 3, 8, 13 ),
  is_summary = c( rep( FALSE, nrow( prop_cc_summary_heterosexual ) - 1 ), TRUE ),
  sizes = 0.4,
  
  ref_line = c( prop_cc_summary_heterosexual[ prop_cc_summary_heterosexual$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2010*100,
                prop_cc_summary_heterosexual[ prop_cc_summary_heterosexual$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2014*100,
                prop_cc_summary_heterosexual[ prop_cc_summary_heterosexual$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2021*100 ),
  
  vert_line = prop_cc_summary_heterosexual[ prop_cc_summary_heterosexual$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2010*100,
    
  xlim = list( c( 90, 100 ), c( 60, 100 ), c( 60, 100 ) ),
  ticks_at = list( c( 90, 95, 100 ), c( 60, 80, 100 ), c( 60, 80, 100 ) ),
  xlab = "Proportion (%) (95% CI)",
  theme = tm
  )

p_cc_heterosexual <- edit_plot(
  p_cc_heterosexual,
  row = c(1, 4, 9, 13, 17, 22, 26, 29, 32),
  gp = gpar(fontface = "bold")
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "Heterosexual, Proportion (%) (95% CI)",
  col = 3:4,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "SSᵃ",
  col = 6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "SSᵃ",
  col = 11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "SSᵃ",
  col = 16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- insert_text(
  p_cc_heterosexual,
  text = "SPHC-B 2010",
  col = 3:6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "SPHC-B 2014",
  col = 8:11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "Heterosexual, Proportion (%) (95% CI)",
  col = 8:9,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "SPHC-B 2021",
  col = 13:16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_text(
  p_cc_heterosexual,
  text = "Heterosexual, Proportion (%) (95% CI)",
  col = 13:14,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_heterosexual <- add_border(
  p_cc_heterosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 3:6,
  gp = gpar(lwd = 1)
)

p_cc_heterosexual <- add_border(
  p_cc_heterosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 8:11,
  gp = gpar(lwd = 1)
)

p_cc_heterosexual <- add_border(
  p_cc_heterosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 13:16,
  gp = gpar(lwd = 1)
)
 
plot( p_cc_heterosexual )
```

##### 3.1.3. Homosexual group
```{r}
prop_cc_summary_homosexual <- prop_cc_summary[ -c( 9:17 ), c( 1, 5:7, 14, 18:20, 27, 31:33, 40 ) ]

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 2 )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( "SPHC-B 2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_upper_ci_2010*100 ), ")" ),
    .before = 3 )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 8 )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( "SPHC-B 2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_upper_ci_2014*100 ), ")" ),
    .before = 9 )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 14 )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>% 
  add_column( "SPHC-B 2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_point_estimate_2021*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_lower_ci_2021*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_homosexual$Homosexual_upper_ci_2021*100 ), ")"  ),
    .before = 15 )

prop_cc_summary_homosexual$`SPHC-B 2010` <- ifelse( 
  is.na( prop_cc_summary_homosexual$Homosexual_point_estimate_2010 ), "",
  prop_cc_summary_homosexual$`SPHC-B 2010` )

prop_cc_summary_homosexual$`SPHC-B 2014` <- ifelse( 
  is.na( prop_cc_summary_homosexual$Homosexual_point_estimate_2014 ), "",
  prop_cc_summary_homosexual$`SPHC-B 2014` )

prop_cc_summary_homosexual$`SPHC-B 2021` <- ifelse( 
  is.na( prop_cc_summary_homosexual$Homosexual_point_estimate_2010 ) &
    is.na( prop_cc_summary_homosexual$Homosexual_point_estimate_2021 ), "",
  ifelse( is.na( prop_cc_summary_homosexual$Homosexual_point_estimate_2021 ), "\u2013",
          prop_cc_summary_homosexual$`SPHC-B 2021` ) )

prop_cc_summary_homosexual <- prop_cc_summary_homosexual %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 8 ) %>%
  add_column( temp3 = " ", .before = 10 ) %>%
  add_column( temp4 = " ", .before = 16 ) %>%
  add_column( temp5 = " ", .before = 18 ) %>%
  add_column( temp6 = " ", .before = 24 )

names( prop_cc_summary_homosexual )[ names( prop_cc_summary_homosexual ) %in% c( "temp1", "temp2", "temp3", "temp4", "temp5", "temp6" ) ] <- ""

colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "SPHC-B 2010" ] <- ""
colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "SPHC-B 2014" ] <- ""
colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "SPHC-B 2021" ] <- ""

colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "sample_size_2010" ] <- ""
colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "sample_size_2014" ] <- ""
colnames( prop_cc_summary_homosexual )[ colnames( prop_cc_summary_homosexual ) == "sample_size_2021" ] <- ""

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ), 
  base_family = "Arial",
  ci_col = "red",
  refline_lty = "dotted",
  refline_lwd = 1,
  refline_col = "steelblue",
  vertline_lty = "dashed",
  vertline_lwd = 1,
  vertline_col = "steelblue",
  summary_col = "#4575b4",
  summary_fill = "#4575b4"
)

p_cc_homosexual <- forest(
  prop_cc_summary_homosexual[ , c( 1:4, 8:12, 16:20, 24, 25 ) ],
  
  est = list( prop_cc_summary_homosexual$Homosexual_point_estimate_2010*100,
              prop_cc_summary_homosexual$Homosexual_point_estimate_2014*100,
              prop_cc_summary_homosexual$Homosexual_point_estimate_2021*100
  ),
  
  lower = list( prop_cc_summary_homosexual$Homosexual_lower_ci_2010*100,
                prop_cc_summary_homosexual$Homosexual_lower_ci_2014*100,
                prop_cc_summary_homosexual$Homosexual_lower_ci_2021*100
  ),
  
  upper = list( prop_cc_summary_homosexual$Homosexual_upper_ci_2010*100,
                prop_cc_summary_homosexual$Homosexual_upper_ci_2014*100,
                prop_cc_summary_homosexual$Homosexual_upper_ci_2021*100
  ),
  
  ci_column = c( 3, 8, 13 ),
  is_summary = c( rep( FALSE, nrow( prop_cc_summary_homosexual ) - 1 ), TRUE ),
  sizes = 0.4,
  
  ref_line = c( prop_cc_summary_homosexual[ prop_cc_summary_homosexual$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2010*100,
                prop_cc_summary_homosexual[ prop_cc_summary_homosexual$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2014*100,
                prop_cc_summary_homosexual[ prop_cc_summary_homosexual$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2021*100 ),
  
  vert_line = prop_cc_summary_homosexual[ prop_cc_summary_homosexual$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2010*100,
  
  xlim = list( c( 0, 4 ), c( 0, 4 ), c( 0, 4 ) ),
  ticks_at = list( c( 0, 1, 2, 3, 4 ), c( 0, 1, 2, 3, 4 ), c( 0, 1, 2, 3, 4 ) ),
  xlab = "Proportion (%) (95% CI)",
  theme = tm
)

p_cc_homosexual <- edit_plot(
  p_cc_homosexual,
  row = c(1, 4, 9, 13, 17, 22, 26, 29, 32),
  gp = gpar(fontface = "bold")
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "Homosexual, Proportion (%) (95% CI)",
  col = 3:4,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "SSᵃ",
  col = 6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "SSᵃ",
  col = 11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "SSᵃ",
  col = 16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- insert_text(
  p_cc_homosexual,
  text = "SPHC-B 2010",
  col = 3:6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "SPHC-B 2014",
  col = 8:11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "Homosexual, Proportion (%) (95% CI)",
  col = 8:9,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "SPHC-B 2021",
  col = 13:16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_text(
  p_cc_homosexual,
  text = "Homosexual, Proportion (%) (95% CI)",
  col = 13:14,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_homosexual <- add_border(
  p_cc_homosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 3:6,
  gp = gpar(lwd = 1)
)

p_cc_homosexual <- add_border(
  p_cc_homosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 8:11,
  gp = gpar(lwd = 1)
)

p_cc_homosexual <- add_border(
  p_cc_homosexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 13:16,
  gp = gpar(lwd = 1)
)

plot( p_cc_homosexual )
```

##### 3.1.4. Bisexual group
```{r}
prop_cc_summary_bisexual <- prop_cc_summary[ -c( 9:17 ), c( 1, 8:10, 14, 21:23, 27, 34:36, 40 ) ]

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 2 )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( "SPHC-B 2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_upper_ci_2010*100 ), ")" ),
    .before = 3 )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 8 )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( "SPHC-B 2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_upper_ci_2014*100 ), ")" ),
    .before = 9 )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 14 )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>% 
  add_column( "SPHC-B 2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_point_estimate_2021*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_lower_ci_2021*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_bisexual$Bisexual_upper_ci_2021*100 ), ")"  ),
    .before = 15 )

prop_cc_summary_bisexual$`SPHC-B 2010` <- ifelse( 
  is.na( prop_cc_summary_bisexual$Bisexual_point_estimate_2010 ), "",
  prop_cc_summary_bisexual$`SPHC-B 2010` )

prop_cc_summary_bisexual$`SPHC-B 2014` <- ifelse( 
  is.na( prop_cc_summary_bisexual$Bisexual_point_estimate_2014 ), "",
  prop_cc_summary_bisexual$`SPHC-B 2014` )

prop_cc_summary_bisexual$`SPHC-B 2021` <- ifelse( 
  is.na( prop_cc_summary_bisexual$Bisexual_point_estimate_2010 ) &
    is.na( prop_cc_summary_bisexual$Bisexual_point_estimate_2021 ), "",
  ifelse( is.na( prop_cc_summary_bisexual$Bisexual_point_estimate_2021 ), "\u2013",
          prop_cc_summary_bisexual$`SPHC-B 2021` ) )

prop_cc_summary_bisexual <- prop_cc_summary_bisexual %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 8 ) %>%
  add_column( temp3 = " ", .before = 10 ) %>%
  add_column( temp4 = " ", .before = 16 ) %>%
  add_column( temp5 = " ", .before = 18 ) %>%
  add_column( temp6 = " ", .before = 24 )

names( prop_cc_summary_bisexual )[ names( prop_cc_summary_bisexual ) %in% c( "temp1", "temp2", "temp3", "temp4", "temp5", "temp6" ) ] <- ""

colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "SPHC-B 2010" ] <- ""
colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "SPHC-B 2014" ] <- ""
colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "SPHC-B 2021" ] <- ""

colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "sample_size_2010" ] <- ""
colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "sample_size_2014" ] <- ""
colnames( prop_cc_summary_bisexual )[ colnames( prop_cc_summary_bisexual ) == "sample_size_2021" ] <- ""

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ), 
  base_family = "Arial",
  ci_col = "red",
  refline_lty = "dotted",
  refline_lwd = 1,
  refline_col = "steelblue",
  vertline_lty = "dashed",
  vertline_lwd = 1,
  vertline_col = "steelblue",
  summary_col = "#4575b4",
  summary_fill = "#4575b4"
)

p_cc_bisexual <- forest(
  prop_cc_summary_bisexual[ , c( 1:4, 8:12, 16:20, 24, 25 ) ],
  
  est = list( prop_cc_summary_bisexual$Bisexual_point_estimate_2010*100,
              prop_cc_summary_bisexual$Bisexual_point_estimate_2014*100,
              prop_cc_summary_bisexual$Bisexual_point_estimate_2021*100
  ),
  
  lower = list( prop_cc_summary_bisexual$Bisexual_lower_ci_2010*100,
                prop_cc_summary_bisexual$Bisexual_lower_ci_2014*100,
                prop_cc_summary_bisexual$Bisexual_lower_ci_2021*100
  ),
  
  upper = list( prop_cc_summary_bisexual$Bisexual_upper_ci_2010*100,
                prop_cc_summary_bisexual$Bisexual_upper_ci_2014*100,
                prop_cc_summary_bisexual$Bisexual_upper_ci_2021*100
  ),
  
  ci_column = c( 3, 8, 13 ),
  is_summary = c( rep( FALSE, nrow( prop_cc_summary_bisexual ) - 1 ), TRUE ),
  sizes = 0.4,
  
  ref_line = c( prop_cc_summary_bisexual[ prop_cc_summary_bisexual$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2010*100,
                prop_cc_summary_bisexual[ prop_cc_summary_bisexual$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2014*100,
                prop_cc_summary_bisexual[ prop_cc_summary_bisexual$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2021*100 ),
  
  vert_line = prop_cc_summary_bisexual[ prop_cc_summary_bisexual$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2010*100,
  
  xlim = list( c( 0, 5 ), c( 0, 10 ), c( 0, 10 ) ),
  ticks_at = list( c( 0, 1, 2, 3, 4, 5 ), c( 0, 2, 4, 6, 8, 10 ), c( 0, 2, 4, 6, 8, 10 ) ),
  xlab = "Proportion (%) (95% CI)",
  theme = tm
)

p_cc_bisexual <- edit_plot(
  p_cc_bisexual,
  row = c(1, 4, 9, 13, 17, 22, 26, 29, 32),
  gp = gpar(fontface = "bold")
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "Bisexual, Proportion (%) (95% CI)",
  col = 3:4,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "SSᵃ",
  col = 6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "SSᵃ",
  col = 11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "SSᵃ",
  col = 16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- insert_text(
  p_cc_bisexual,
  text = "SPHC-B 2010",
  col = 3:6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "SPHC-B 2014",
  col = 8:11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "Bisexual, Proportion (%) (95% CI)",
  col = 8:9,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "SPHC-B 2021",
  col = 13:16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_text(
  p_cc_bisexual,
  text = "Bisexual, Proportion (%) (95% CI)",
  col = 13:14,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_bisexual <- add_border(
  p_cc_bisexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 3:6,
  gp = gpar(lwd = 1)
)

p_cc_bisexual <- add_border(
  p_cc_bisexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 8:11,
  gp = gpar(lwd = 1)
)

p_cc_bisexual <- add_border(
  p_cc_bisexual,
  part = "header",
  row = 1,
  where = "bottom",
  col = 13:16,
  gp = gpar(lwd = 1)
)

plot( p_cc_bisexual )
```

##### 3.1.5. Other group
```{r}
prop_cc_summary_other <- prop_cc_summary[ -c( 9:17 ), c( 1, 11:13, 14, 24:26, 27, 37:39, 40 ) ]

prop_cc_summary_other$Subgroup[ prop_cc_summary_other$Subgroup == "   16–29 yrsᵇ" ] <- "   16–29 yrsᶜ"
prop_cc_summary_other$Subgroup[ prop_cc_summary_other$Subgroup == "   Europeᶜ" ] <- "   Europeᵈ"
prop_cc_summary_other$Subgroup[ prop_cc_summary_other$Subgroup == "Income (100 kr/yr)ᵈ" ] <- "Income (100 kr/yr)ᵉ"
prop_cc_summary_other$Subgroup[ prop_cc_summary_other$Subgroup == "Marital statusᵉ" ] <- "Marital statusᶠ"

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 2 )

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( "SPHC-B 2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_other$Uncertain_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_other$Uncertain_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_other$Uncertain_upper_ci_2010*100 ), ")" ),
    .before = 3 )

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 8 )

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( "SPHC-B 2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_point_estimate_2014`*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_lower_ci_2014`*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_upper_ci_2014`*100 ), ")" ),
    .before = 9 )

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 14 )

prop_cc_summary_other <- prop_cc_summary_other %>% 
  add_column( "SPHC-B 2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_point_estimate_2021`*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_lower_ci_2021`*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_other$`None of the above_upper_ci_2021`*100 ), ")"  ),
    .before = 15 )

prop_cc_summary_other$`SPHC-B 2010` <- ifelse( 
  is.na( prop_cc_summary_other$Uncertain_point_estimate_2010 ), "",
  prop_cc_summary_other$`SPHC-B 2010` )

prop_cc_summary_other$`SPHC-B 2014` <- ifelse( 
  is.na( prop_cc_summary_other$`None of the above_point_estimate_2014` ), "",
  prop_cc_summary_other$`SPHC-B 2014` )

prop_cc_summary_other$`SPHC-B 2021` <- ifelse( 
  is.na( prop_cc_summary_other$Uncertain_point_estimate_2010 ) &
    is.na( prop_cc_summary_other$`None of the above_point_estimate_2021` ), "",
  ifelse( is.na( prop_cc_summary_other$`None of the above_point_estimate_2021` ), "\u2013",
          prop_cc_summary_other$`SPHC-B 2021` ) )

prop_cc_summary_other <- prop_cc_summary_other %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 8 ) %>%
  add_column( temp3 = " ", .before = 10 ) %>%
  add_column( temp4 = " ", .before = 16 ) %>%
  add_column( temp5 = " ", .before = 18 ) %>%
  add_column( temp6 = " ", .before = 24 )

names( prop_cc_summary_other )[ names( prop_cc_summary_other ) %in% c( "temp1", "temp2", "temp3", "temp4", "temp5", "temp6" ) ] <- ""

colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "SPHC-B 2010" ] <- ""
colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "SPHC-B 2014" ] <- ""
colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "SPHC-B 2021" ] <- ""

colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "sample_size_2010" ] <- ""
colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "sample_size_2014" ] <- ""
colnames( prop_cc_summary_other )[ colnames( prop_cc_summary_other ) == "sample_size_2021" ] <- ""

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ), 
  base_family = "Arial",
  ci_col = "red",
  refline_lty = "dotted",
  refline_lwd = 1,
  refline_col = "steelblue",
  vertline_lty = "dashed",
  vertline_lwd = 1,
  vertline_col = "steelblue",
  summary_col = "#4575b4",
  summary_fill = "#4575b4"
)

p_cc_other <- forest(
  prop_cc_summary_other[ , c( 1:4, 8:12, 16:20, 24, 25 ) ],
  
  est = list( prop_cc_summary_other$Uncertain_point_estimate_2010*100,
              prop_cc_summary_other$`None of the above_point_estimate_2014`*100,
              prop_cc_summary_other$`None of the above_point_estimate_2021`*100
  ),
  
  lower = list( prop_cc_summary_other$Uncertain_lower_ci_2010*100,
                prop_cc_summary_other$`None of the above_lower_ci_2014`*100,
                prop_cc_summary_other$`None of the above_lower_ci_2021`*100
  ),
  
  upper = list( prop_cc_summary_other$Uncertain_upper_ci_2010*100,
                prop_cc_summary_other$`None of the above_upper_ci_2014`*100,
                prop_cc_summary_other$`None of the above_upper_ci_2021`*100
  ),
  
  ci_column = c( 3, 8, 13 ),
  is_summary = c( rep( FALSE, nrow( prop_cc_summary_other ) - 1 ), TRUE ),
  sizes = 0.4,
  
  ref_line = c( prop_cc_summary_other[ prop_cc_summary_other$Subgroup == "Stockholm County", ]$Uncertain_point_estimate_2010*100,
                prop_cc_summary_other[ prop_cc_summary_other$Subgroup == "Stockholm County", ]$`None of the above_point_estimate_2014`*100,
                prop_cc_summary_other[ prop_cc_summary_other$Subgroup == "Stockholm County", ]$`None of the above_point_estimate_2021`*100 ),
  
  vert_line = prop_cc_summary_other[ prop_cc_summary_other$Subgroup == "Stockholm County", ]$Uncertain_point_estimate_2010*100,
  
  xlim = list( c( 0, 6 ), c( 0, 30 ), c( 0, 30 ) ),
  ticks_at = list( c( 0, 3, 6 ), c( 0, 5, 10, 15, 20, 25, 30 ), c( 0, 5, 10, 15, 20, 25, 30 ) ),
  xlab = "Proportion (%) (95% CI)",
  theme = tm
)

p_cc_other <- edit_plot(
  p_cc_other,
  row = c(1, 4, 9, 13, 17, 22, 26, 29, 32),
  gp = gpar(fontface = "bold")
)

p_cc_other <- add_text(
  p_cc_other,
  text = "Uncertain, Proportion (%) (95% CI)",
  col = 3:4,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "SSᵃ",
  col = 6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "SSᵃ",
  col = 11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "SSᵃ",
  col = 16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- insert_text(
  p_cc_other,
  text = "SPHC-B 2010",
  col = 3:6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "SPHC-B 2014",
  col = 8:11,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "Otherᵇ, Proportion (%) (95% CI)",
  col = 8:9,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "SPHC-B 2021",
  col = 13:16,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_text(
  p_cc_other,
  text = "Otherᵇ, Proportion (%) (95% CI)",
  col = 13:14,
  row = 2,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_other <- add_border(
  p_cc_other,
  part = "header",
  row = 1,
  where = "bottom",
  col = 3:6,
  gp = gpar(lwd = 1)
)

p_cc_other <- add_border(
  p_cc_other,
  part = "header",
  row = 1,
  where = "bottom",
  col = 8:11,
  gp = gpar(lwd = 1)
)

p_cc_other <- add_border(
  p_cc_other,
  part = "header",
  row = 1,
  where = "bottom",
  col = 13:16,
  gp = gpar(lwd = 1)
)

plot( p_cc_other )
```

##### 3.1.6. Age by sex
```{r}
prop_cc_summary_age_sex <- prop_cc_summary[ c( 10:17 ), ]

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_row( Subgroup = "Male", .before = 1 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_row( Subgroup = "Female", .before = 6 )

prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Male: 16–29 yrsᵇ" ] <- "   16–29 yrsᶜ\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Male: 30–44 yrs" ] <- "   30–44 yrs\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Male: 45–59 yrs" ] <- "   45–59 yrs\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Male: \u2265 60 yrs" ] <- "   \u2265 60 yrs\n\n"

prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Female: 16–29 yrsᵇ" ] <- "   16–29 yrsᶜ\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Female: 30–44 yrs" ] <- "   30–44 yrs\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Female: 45–59 yrs" ] <- "   45–59 yrs\n\n"
prop_cc_summary_age_sex$Subgroup[ prop_cc_summary_age_sex$Subgroup == "   Female: \u2265 60 yrs" ] <- "   \u2265 60 yrs\n\n"

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Heterosexual_2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_upper_ci_2010*100 ), ")" ),
    .before = 2 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Homosexual_2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_upper_ci_2010*100 ), ")" ),
    .before = 6 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Bisexual_2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_upper_ci_2010*100 ), ")" ),
    .before = 10 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Other_2010" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Uncertain_point_estimate_2010*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Uncertain_lower_ci_2010*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Uncertain_upper_ci_2010*100 ), ")" ),
    .before = 14 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Heterosexual_2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_upper_ci_2014*100 ), ")" ),
    .before = 19 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Homosexual_2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_upper_ci_2014*100 ), ")" ),
    .before = 23 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Bisexual_2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_point_estimate_2014*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_lower_ci_2014*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_upper_ci_2014*100 ), ")" ),
    .before = 27 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Other_2014" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_point_estimate_2014`*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_lower_ci_2014`*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_upper_ci_2014`*100 ), ")" ),
    .before = 31 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Heterosexual_2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_point_estimate_2021*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_lower_ci_2021*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Heterosexual_upper_ci_2021*100 ), ")" ),
    .before = 36 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Homosexual_2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_point_estimate_2021*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_lower_ci_2021*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Homosexual_upper_ci_2021*100 ), ")" ),
    .before = 40 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Bisexual_2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_point_estimate_2021*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_lower_ci_2021*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$Bisexual_upper_ci_2021*100 ), ")" ),
    .before = 44 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Other_2021" = paste0(
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_point_estimate_2021`*100 ), " (", 
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_lower_ci_2021`*100 ), ", ", 
    sprintf( "%.1f", prop_cc_summary_age_sex$`None of the above_upper_ci_2021`*100 ), ")" ),
    .before = 48 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Heterosexual" = paste( prop_cc_summary_age_sex$`Heterosexual_2010`,
                                      prop_cc_summary_age_sex$`Heterosexual_2014`,
                                      prop_cc_summary_age_sex$`Heterosexual_2021`,
                                      sep = "\n" ),
              .before = 2 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Homosexual" = paste( prop_cc_summary_age_sex$`Homosexual_2010`,
                                    prop_cc_summary_age_sex$`Homosexual_2014`,
                                    prop_cc_summary_age_sex$`Homosexual_2021`,
                                    sep = "\n" ),
              .before = 3 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Bisexual" = paste( prop_cc_summary_age_sex$`Bisexual_2010`,
                                  prop_cc_summary_age_sex$`Bisexual_2014`,
                                  prop_cc_summary_age_sex$`Bisexual_2021`,
                                  sep = "\n" ),
              .before = 4 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Otherᵇ" = paste( prop_cc_summary_age_sex$`Other_2010`,
                                prop_cc_summary_age_sex$`Other_2014`,
                                prop_cc_summary_age_sex$`Other_2021`,
                                sep = "\n" ),
              .before = 5 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( "Nᵃ" = paste( prop_cc_summary_age_sex$sample_size_2010,
                            prop_cc_summary_age_sex$sample_size_2014,
                            prop_cc_summary_age_sex$sample_size_2021,
                            sep = "\n" ),
              .before = 2 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 3 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 5 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 7 )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>% 
  add_column( `    ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 9 )

prop_cc_summary_age_sex$`Nᵃ` <- ifelse( is.na( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010 ), "",
                                      prop_cc_summary_age_sex$`Nᵃ` )

prop_cc_summary_age_sex$`Heterosexual` <- ifelse( is.na( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010 ), "",
                                                   prop_cc_summary_age_sex$`Heterosexual` )

prop_cc_summary_age_sex$`Homosexual` <- ifelse( is.na( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010 ), "",
                                                 prop_cc_summary_age_sex$`Homosexual` )

prop_cc_summary_age_sex$`Bisexual` <- ifelse( is.na( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010 ), "",
                                               prop_cc_summary_age_sex$`Bisexual` )

prop_cc_summary_age_sex$`Otherᵇ` <- ifelse( is.na( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010 ), "",
                                                   prop_cc_summary_age_sex$`Otherᵇ` )

prop_cc_summary_age_sex <- prop_cc_summary_age_sex %>%
  add_column( temp1 = " ", .before = 2 ) %>%
  add_column( temp2 = " ", .before = 4 ) %>%
  add_column( temp3 = " ", .before = 7 ) %>%
  add_column( temp4 = " ", .before = 10 ) %>%
  add_column( temp5 = " ", .before = 13 )

names( prop_cc_summary_age_sex )[ names( prop_cc_summary_age_sex ) %in% c( "temp1", "temp2", "temp3", "temp4", "temp5" ) ] <- ""

colnames( prop_cc_summary_age_sex )[ colnames( prop_cc_summary_age_sex ) == "Nᵃ" ] <- ""
colnames( prop_cc_summary_age_sex )[ colnames( prop_cc_summary_age_sex ) == "Heterosexual" ] <- ""
colnames( prop_cc_summary_age_sex )[ colnames( prop_cc_summary_age_sex ) == "Homosexual" ] <- ""
colnames( prop_cc_summary_age_sex )[ colnames( prop_cc_summary_age_sex ) == "Bisexual" ] <- ""
colnames( prop_cc_summary_age_sex )[ colnames( prop_cc_summary_age_sex ) == "Otherᵇ" ] <- ""

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ),
  legend_value = c( "SPHC-B 2010", "SPHC-B 2014", "SPHC-B 2021" ),
  legend_name = NULL,
  legend_position = "right",
  base_family = "Arial",
  refline_lty = "dashed",
  refline_lwd = 1,
  refline_col = "#DF536B",
  vertline_lty = "dashed",
  vertline_lwd = 1,
  vertline_col = c( "#2297E6", "#61D04F" )
  )

p_cc_age_sex <- forest(
  prop_cc_summary_age_sex[ , 1:15 ],
  
  est = list( prop_cc_summary_age_sex$Heterosexual_point_estimate_2010*100,
              prop_cc_summary_age_sex$Homosexual_point_estimate_2010*100,
              prop_cc_summary_age_sex$Bisexual_point_estimate_2010*100,
              prop_cc_summary_age_sex$Uncertain_point_estimate_2010*100,
              prop_cc_summary_age_sex$Heterosexual_point_estimate_2014*100,
              prop_cc_summary_age_sex$Homosexual_point_estimate_2014*100,
              prop_cc_summary_age_sex$Bisexual_point_estimate_2014*100,
              prop_cc_summary_age_sex$`None of the above_point_estimate_2014`*100,
              prop_cc_summary_age_sex$Heterosexual_point_estimate_2021*100,
              prop_cc_summary_age_sex$Homosexual_point_estimate_2021*100,
              prop_cc_summary_age_sex$Bisexual_point_estimate_2021*100,
              prop_cc_summary_age_sex$`None of the above_point_estimate_2021`*100
              ),
  
  lower = list( prop_cc_summary_age_sex$Heterosexual_lower_ci_2010*100,
                prop_cc_summary_age_sex$Homosexual_lower_ci_2010*100,
                prop_cc_summary_age_sex$Bisexual_lower_ci_2010*100,
                prop_cc_summary_age_sex$Uncertain_lower_ci_2010*100,
                prop_cc_summary_age_sex$Heterosexual_lower_ci_2014*100,
                prop_cc_summary_age_sex$Homosexual_lower_ci_2014*100,
                prop_cc_summary_age_sex$Bisexual_lower_ci_2014*100,
                prop_cc_summary_age_sex$`None of the above_lower_ci_2014`*100,
                prop_cc_summary_age_sex$Heterosexual_lower_ci_2021*100,
                prop_cc_summary_age_sex$Homosexual_lower_ci_2021*100,
                prop_cc_summary_age_sex$Bisexual_lower_ci_2021*100,
                prop_cc_summary_age_sex$`None of the above_lower_ci_2021`*100
                ),
  
  upper = list( prop_cc_summary_age_sex$Heterosexual_upper_ci_2010*100,
                prop_cc_summary_age_sex$Homosexual_upper_ci_2010*100,
                prop_cc_summary_age_sex$Bisexual_upper_ci_2010*100,
                prop_cc_summary_age_sex$Uncertain_upper_ci_2010*100,
                prop_cc_summary_age_sex$Heterosexual_upper_ci_2014*100,
                prop_cc_summary_age_sex$Homosexual_upper_ci_2014*100,
                prop_cc_summary_age_sex$Bisexual_upper_ci_2014*100,
                prop_cc_summary_age_sex$`None of the above_upper_ci_2014`*100,
                prop_cc_summary_age_sex$Heterosexual_upper_ci_2021*100,
                prop_cc_summary_age_sex$Homosexual_upper_ci_2021*100,
                prop_cc_summary_age_sex$Bisexual_upper_ci_2021*100,
                prop_cc_summary_age_sex$`None of the above_upper_ci_2021`*100
                ),
  
  ci_column = c( 5, 8, 11, 14 ),
  sizes = 0.4,
  
  ref_line = c( 
    prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2010*100,
    prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2010*100,
    prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2010*100,
    prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Uncertain_point_estimate_2010*100
    ),
  
  vert_line = list(
    c( prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2014*100,
       prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Heterosexual_point_estimate_2021*100 ), 
    c( prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2014*100,
       prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Homosexual_point_estimate_2021*100 ),
    c( prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2014*100,
       prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$Bisexual_point_estimate_2021*100 ),
    c( prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$`None of the above_point_estimate_2014`*100,
       prop_cc_summary[ prop_cc_summary$Subgroup == "Stockholm County", ]$`None of the above_point_estimate_2021`*100 )
    ),
  
  xlim = list( c( 70, 100 ), c( 0, 5 ), c( 0, 15 ), c( 0, 15 ) ),
  ticks_at = list( c( 70, 80, 90, 100 ), c( 0, 1, 2, 3, 4, 5 ), c( 0, 5, 10, 15 ), c( 0, 5, 10, 15 ) ),
  
  xlab = "Proportion (%) (95% CI)",
  nudge_y = 0.33,
  theme = tm
 )

p_cc_age_sex <- edit_plot(p_cc_age_sex,
                          row = c(1, 6),
                          gp = gpar(fontface = "bold"))

p_cc_age_sex <- add_text(
  p_cc_age_sex,
  text = "SSᵃ",
  col = 3,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_age_sex <- add_text(
  p_cc_age_sex,
  text = "Heterosexual, Proportion (%) (95% CI)",
  col = 5:6,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_age_sex <- add_text(
  p_cc_age_sex,
  text = "Homosexual, Proportion (%) (95% CI)",
  col = 8:9,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_age_sex <- add_text(
  p_cc_age_sex,
  text = "Bisexual, Proportion (%) (95% CI)",
  col = 11:12,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

p_cc_age_sex <- add_text(
  p_cc_age_sex,
  text = "Uncertain/Otherᵇ, Proportion (%) (95% CI)",
  col = 14:15,
  row = 1,
  part = "header",
  gp = gpar(
    fontface = "bold",
    fontsize = 10,
    fontfamily = "Arial"
  )
)

plot( p_cc_age_sex )
```

### 4. Forest Plots for Relation between Sexual Identity and Demographic Factors
#### 4.1. Complete-case analysis
```{r}
output1_cc_2021 <- output1_cc_2021[ c( 2:16, 54 ), ] %>% 
  add_column( ` ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 2 )

output1_cc_2021 <- output1_cc_2021 %>% 
  add_column( " Homosexual\n OR (95% CI)" = paste0(
    " ",
    sprintf( "%.2f", output1_cc_2021$OR_2021_Homosexual ), " (", 
    sprintf( "%.2f", output1_cc_2021$lower_ci_2021_Homosexual ), ", ", 
    sprintf( "%.2f", output1_cc_2021$upper_ci_2021_Homosexual ), ")" ),
    .before = 3 )

output1_cc_2021 <- output1_cc_2021 %>% 
  add_column( `  ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 11 )

output1_cc_2021 <- output1_cc_2021 %>% 
  add_column( " Bisexual\n OR (95% CI)" = paste0(
    " ",
    sprintf( "%.2f", output1_cc_2021$OR_2021_Bisexual ), " (", 
    sprintf( "%.2f", output1_cc_2021$lower_ci_2021_Bisexual ), ", ", 
    sprintf( "%.2f", output1_cc_2021$upper_ci_2021_Bisexual ), ")" ),
    .before = 12 )

output1_cc_2021 <- output1_cc_2021 %>% 
  add_column( `   ` = paste( rep( " ", 20 ) , collapse = " " ), .before = 20 )

output1_cc_2021 <- output1_cc_2021 %>% 
  add_column( " Other\n OR (95% CI)" = paste0(
    sprintf( "%.2f", output1_cc_2021$`OR_2021_None of the above` ), " (", 
    sprintf( "%.2f", output1_cc_2021$`lower_ci_2021_None of the above` ), ", ", 
    sprintf( "%.2f", output1_cc_2021$`upper_ci_2021_None of the above` ), ")" ),
    .before = 21 )

colnames( output1_cc_2021 )[ colnames( output1_cc_2021 ) == "category_2021" ] <- "\nDemographic factors"

tm <- forest_theme(
  base_size = 10,
  colhead = list( fg_params = list( fontsize = 10 ) ), 
  base_family = "Arial",
  ci_col = "red",
  refline_lty = "dashed",
  refline_lwd = 0.8,
  refline_col = "grey"
  )

p <- forest(
  output1_cc_2021[ , c( 1, 2, 3, 11, 12, 20, 21 ) ],
  
  est = list( output1_cc_2021$OR_2021_Homosexual,
              output1_cc_2021$OR_2021_Bisexual,
              output1_cc_2021$`OR_2021_None of the above` ),
  
  lower = list( output1_cc_2021$lower_ci_2021_Homosexual,
                output1_cc_2021$lower_ci_2021_Bisexual,
                output1_cc_2021$`lower_ci_2021_None of the above` ),
  
  upper = list( output1_cc_2021$upper_ci_2021_Homosexual,
                output1_cc_2021$upper_ci_2021_Bisexual,
                output1_cc_2021$`upper_ci_2021_None of the above` ),
  
  ci_column = c( 2, 4, 6 ),
  sizes = 0.4,
  
  ref_line = 1,
  xlim = list( c( 0, 4 ), c( 0, 5 ), c( 0, 10 ) ),
  ticks_at = list( c( 0, 1, 4 ), c( 0, 1, 3, 5 ), c( 0, 1, 5, 10 ) ),
  xlab = "OR (95% CI)",
  theme = tm
  )

plot( p )

#p <- edit_plot( p,
 #               row = nrow( prop_cc_summary_heterosexual ),
  #              gp = gpar( fontface = "bold" ) )


```